### PR TITLE
Replace doi_inactivedate with doi_brokendate

### PR DESCRIPTION
**Pull request by fhocutt**
- Remove "doi_inactivedate" from the list of parameters in DOItools.php
- Remove outdated "doi_inactivedate" parameter/value when DOIs are checked
  (Template.php)
- Update the message in Template::forget()
- Remove "doi_inactivedate" from the giant switch in Template::add_if_new()
- Add doi_inactivedate -> doi_brokendate to the spellchecker's automatic
  corrections (in case any "doi_inactivedate" parameters remain after
  the DOI check)

Test citation: https://test.wikipedia.org/w/index.php?title=User%3AFhocutt+%28WMF%29%2FCitation+bot+test&diff=prev&oldid=244435

From the output to doibot.php: 

```
[..> process> rifydoi]
   . Checking that DOI 10.1126/science.154.3748.509 is operational... [..> process> rifydoi> forget]
   - Dropping parameter doi_inactivedate
   ! Broken doi: 10.1126/science.154.3748.509
```

Pinging reviewers: @kaldari, @Niharika29

### CODE REVIEW

**Comment by kaldari** [comment]
According to the template documentation, doi-broken-date is the currently preferred parameter name and it has the following aliases: doi_brokendate, doi_inactivedate, and doi-inactive-date. It should be easy enough to switch to doi-broken-date and account for the other aliases in Template.php.

**Comment by fhocutt** [comment]
@kaldari: All right, take a look now: https://test.wikipedia.org/w/index.php?title=User%3AFhocutt+%28WMF%29%2FCitation+bot+test&diff=prev&oldid=244572

**Comment by fhocutt** [comment]
You're right, good catch. It should be good now.

**Comment by kaldari** [comment]
+2. Looks good now.

**Comment by fhocutt** [comment]
Merged into the production branch, here: https://github.com/ms609/citation-bot/pull/101

**Pull request merged**
